version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    volumes:
      - "./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf"
      - "./site:/var/www/html"
    ports:
      - "80:80"
    depends_on:
      - php
      - postgres
    networks:
      - app-network

  php:
    container_name: php
    build: ./docker/php
    image: zirionneft/php-fpm
    restart: always
    depends_on:
      - postgres
    volumes:
      - "./site:/var/www/html"
    networks:
      - app-network

  postgres:
    container_name: postgres
    build: ./docker/postgres
    image: zirionneft/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123
      - TZ=GMT
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgresql-data:

networks:
  app-network:
    driver: bridge